apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AliAkbar986/gitops-repo.git'
    targetRevision: HEAD
    path: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/AliAkbar986/gitops-repo.git'
      targetRevision: HEAD
      path: clusters/local
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: production
        syncOptions:
          - CreateNamespace=true
    - repoURL: 'https://github.com/AliAkbar986/gitops-repo.git'
      targetRevision: HEAD
      path: clusters/eks
      destination:
        server: 'https://154DC528F0FB63B054B76A57BDBBFCBF.gr7.us-east-1.eks.amazonaws.com'
        namespace: production
        syncOptions:
          - CreateNamespace=true
    - repoURL: 'https://github.com/AliAkbar986/gitops-repo.git'
      targetRevision: HEAD
      path: clusters/gke
      destination:
        server: 'https://35.193.48.142'
        namespace: production
        syncOptions:
          - CreateNamespace=true
