apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/gitops-repo'
    targetRevision: HEAD
    path: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/your-repo/gitops-repo'
      targetRevision: HEAD
      path: clusters/local
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: production
    - repoURL: 'https://github.com/your-repo/gitops-repo'
      targetRevision: HEAD
      path: clusters/eks
      destination:
        server: '<EKS-API-SERVER-URL>'
        namespace: production
    - repoURL: 'https://github.com/your-repo/gitops-repo'
      targetRevision: HEAD
      path: clusters/gke
      destination:
        server: '<GKE-API-SERVER-URL>'
        namespace: production
