apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/your-repo/gitops-repo'
      revision: HEAD
      directories:
        - path: clusters/*
  template:
    metadata:
      name: '{{path.basename}}-apps'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-repo/gitops-repo'
        targetRevision: HEAD
        path: apps/{{path.basename}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: production
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
