apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: frontend-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---


apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
